///n----------------------------------------------------------------------

export/nfunction/ntimeline(theme)/n{
/n/nreturn/n{
/n/n/n/nMuiTimelineDot:/n{
/n/n/n/n/n/nstyleOverrides:/n{
/n/n/n/n/n/n/n/nroot:/n{
/n/n/n/n/n/n/n/n/n/nboxShadow:/n'none',
/n/n/n/n/n/n/n/n},
/n/n/n/n/n/n},
/n/n/n/n},
/n/n/n/nMuiTimelineConnector:/n{
/n/n/n/n/n/nstyleOverrides:/n{
/n/n/n/n/n/n/n/nroot:/n{
/n/n/n/n/n/n/n/n/n/nbackgroundColor:/ntheme.palette.divider,
/n/n/n/n/n/n/n/n},
/n/n/n/n/n/n},
/n/n/n/n},
/n/n};
}
