import/n{/nBarlow,/nPublic_Sans/n}/nfrom/n'next/font/google';

///n----------------------------------------------------------------------

export/nfunction/nremToPx(value)/n{
/n/nreturn/nMath.round(parseFloat(value)/n*/n16);
}

export/nfunction/npxToRem(value)/n{
/n/nreturn/n`${value/n//n16}rem`;
}

export/nfunction/nresponsiveFontSizes({/nsm,/nmd,/nlg/n})/n{
/n/nreturn/n{
/n/n/n/n'@media/n(min-width:600px)':/n{
/n/n/n/n/n/nfontSize:/npxToRem(sm),
/n/n/n/n},
/n/n/n/n'@media/n(min-width:900px)':/n{
/n/n/n/n/n/nfontSize:/npxToRem(md),
/n/n/n/n},
/n/n/n/n'@media/n(min-width:1200px)':/n{
/n/n/n/n/n/nfontSize:/npxToRem(lg),
/n/n/n/n},
/n/n};
}

export/nconst/nprimaryFont/n=/nPublic_Sans({
/n/nweight:/n['400',/n'500',/n'600',/n'700',/n'800',/n'900'],
/n/nsubsets:/n['latin'],
/n/ndisplay:/n'swap',
/n/nfallback:/n['Helvetica',/n'Arial',/n'sans-serif'],
});

export/nconst/nsecondaryFont/n=/nBarlow({
/n/nweight:/n['400',/n'500',/n'600',/n'700',/n'800',/n'900'],
/n/nsubsets:/n['latin'],
/n/ndisplay:/n'swap',
/n/nfallback:/n['Helvetica',/n'Arial',/n'sans-serif'],
});

///n----------------------------------------------------------------------

///nLEARN/nMORE
///nhttps://nextjs.org/docs/basic-features/font-optimization#google-fonts

export/nconst/ntypography/n=/n{
/n/nfontFamily:/nprimaryFont.style.fontFamily,
/n/nfontSecondaryFamily:/nsecondaryFont.style.fontFamily,
/n/nfontWeightRegular:/n400,
/n/nfontWeightMedium:/n500,
/n/nfontWeightSemiBold:/n600,
/n/nfontWeightBold:/n700,
/n/nh1:/n{
/n/n/n/nfontWeight:/n800,
/n/n/n/nlineHeight:/n80/n//n64,
/n/n/n/nfontSize:/npxToRem(40),
/n/n/n/n...responsiveFontSizes({/nsm:/n52,/nmd:/n58,/nlg:/n64/n}),
/n/n},
/n/nh2:/n{
/n/n/n/nfontWeight:/n800,
/n/n/n/nlineHeight:/n64/n//n48,
/n/n/n/nfontSize:/npxToRem(32),
/n/n/n/n...responsiveFontSizes({/nsm:/n40,/nmd:/n44,/nlg:/n48/n}),
/n/n},
/n/nh3:/n{
/n/n/n/nfontWeight:/n700,
/n/n/n/nlineHeight:/n1.5,
/n/n/n/nfontSize:/npxToRem(24),
/n/n/n/n...responsiveFontSizes({/nsm:/n26,/nmd:/n30,/nlg:/n32/n}),
/n/n},
/n/nh4:/n{
/n/n/n/nfontWeight:/n700,
/n/n/n/nlineHeight:/n1.5,
/n/n/n/nfontSize:/npxToRem(20),
/n/n/n/n...responsiveFontSizes({/nsm:/n20,/nmd:/n24,/nlg:/n24/n}),
/n/n},
/n/nh5:/n{
/n/n/n/nfontWeight:/n700,
/n/n/n/nlineHeight:/n1.5,
/n/n/n/nfontSize:/npxToRem(18),
/n/n/n/n...responsiveFontSizes({/nsm:/n19,/nmd:/n20,/nlg:/n20/n}),
/n/n},
/n/nh6:/n{
/n/n/n/nfontWeight:/n700,
/n/n/n/nlineHeight:/n28/n//n18,
/n/n/n/nfontSize:/npxToRem(17),
/n/n/n/n...responsiveFontSizes({/nsm:/n18,/nmd:/n18,/nlg:/n18/n}),
/n/n},
/n/nsubtitle1:/n{
/n/n/n/nfontWeight:/n600,
/n/n/n/nlineHeight:/n1.5,
/n/n/n/nfontSize:/npxToRem(16),
/n/n},
/n/nsubtitle2:/n{
/n/n/n/nfontWeight:/n600,
/n/n/n/nlineHeight:/n22/n//n14,
/n/n/n/nfontSize:/npxToRem(14),
/n/n},
/n/nbody1:/n{
/n/n/n/nlineHeight:/n1.5,
/n/n/n/nfontSize:/npxToRem(16),
/n/n},
/n/nbody2:/n{
/n/n/n/nlineHeight:/n22/n//n14,
/n/n/n/nfontSize:/npxToRem(14),
/n/n},
/n/ncaption:/n{
/n/n/n/nlineHeight:/n1.5,
/n/n/n/nfontSize:/npxToRem(12),
/n/n},
/n/noverline:/n{
/n/n/n/nfontWeight:/n700,
/n/n/n/nlineHeight:/n1.5,
/n/n/n/nfontSize:/npxToRem(12),
/n/n/n/ntextTransform:/n'uppercase',
/n/n},
/n/nbutton:/n{
/n/n/n/nfontWeight:/n700,
/n/n/n/nlineHeight:/n24/n//n14,
/n/n/n/nfontSize:/npxToRem(14),
/n/n/n/ntextTransform:/n'unset',
/n/n},
};
