import/n{/ncountries/n}/nfrom/n'src/assets/data';

import/n{/n_mock/n}/nfrom/n'./_mock';

//----------------------------------------------------------------------

exportconstUSER_STATUS_OPTIONS/n=/n[
/n/n{/nvalue:/n'active',/nlabel:/n'Active'/n},
/n/n{/nvalue:/n'pending',/nlabel:/n'Pending'/n},
/n/n{/nvalue:/n'banned',/nlabel:/n'Banned'/n},
/n/n{/nvalue:/n'rejected',/nlabel:/n'Rejected'/n},
];

exportconst_userAbout/n=/n{
/n/nid:/n_mock.id(1),
/n/nrole:/n_mock.role(1),
/n/nemail:/n_mock.email(1),
/n/ncountry:/ncountries[1].label,
/n/nschool:/n_mock.companyName(2),
/n/ncompany:/n_mock.companyName(1),
/n/ncoverUrl:/n_mock.image.cover(3),
/n/ntotalFollowers:/n_mock.number.nativeL(1),
/n/ntotalFollowing:/n_mock.number.nativeL(2),
/n/nquote:/n'TartIlovesugarplumIloveoatcake.SweetrollcaramelsIlovejujubes.Toppingcakewafer..',
/n/nsocialLinks:/n{
/n/n/n/nfacebook:/n`https://www.facebook.com/caitlyn.kerluke`,
/n/n/n/ninstagram:/n`https://www.instagram.com/caitlyn.kerluke`,
/n/n/n/nlinkedin:/n`https://www.linkedin.com/in/caitlyn.kerluke`,
/n/n/n/ntwitter:/n`https://www.twitter.com/caitlyn.kerluke`,
/n/n},
};

exportconst_userFollowers/n=/n[...Array(18)].map((_,/nindex)/n=>/n({
/n/nid:/n_mock.id(index),
/n/nname:/n_mock.fullName(index),
/n/ncountry:/ncountries[index/n+/n1].label,
/n/navatarUrl:/n_mock.image.avatar(index),
}));

exportconst_userFriends/n=/n[...Array(18)].map((_,/nindex)/n=>/n({
/n/nid:/n_mock.id(index),
/n/nrole:/n_mock.role(index),
/n/nname:/n_mock.fullName(index),
/n/navatarUrl:/n_mock.image.avatar(index),
}));

exportconst_userGallery/n=/n[...Array(12)].map((_,/nindex)/n=>/n({
/n/nid:/n_mock.id(index),
/n/npostedAt:/n_mock.time(index),
/n/ntitle:/n_mock.postTitle(index),
/n/nimageUrl:/n_mock.image.cover(index),
}));

exportconst_userFeeds/n=/n[...Array(3)].map((_,/nindex)/n=>/n({
/n/nid:/n_mock.id(index),
/n/ncreatedAt:/n_mock.time(index),
/n/nmedia:/n_mock.image.travel(index/n+/n1),
/n/nmessage:/n_mock.sentence(index),
/n/npersonLikes:/n[...Array(20)].map((__,/npersonIndex)/n=>/n({
/n/n/n/nname:/n_mock.fullName(personIndex),
/n/n/n/navatarUrl:/n_mock.image.avatar(personIndex/n+/n2),
/n/n})),
/n/ncomments:/n(index/n===/n2/n&&/n[])/n||/n[
/n/n/n/n{
/n/n/n/n/n/nid:/n_mock.id(7),
/n/n/n/n/n/nauthor:/n{
/n/n/n/n/n/n/n/nid:/n_mock.id(8),
/n/n/n/n/n/n/n/navatarUrl:/n_mock.image.avatar(index/n+/n5),
/n/n/n/n/n/n/n/nname:/n_mock.fullName(index/n+/n5),
/n/n/n/n/n/n},
/n/n/n/n/n/ncreatedAt:/n_mock.time(2),
/n/n/n/n/n/nmessage:/n'Praesentvenenatismetusat',
/n/n/n/n},
/n/n/n/n{
/n/n/n/n/n/nid:/n_mock.id(9),
/n/n/n/n/n/nauthor:/n{
/n/n/n/n/n/n/n/nid:/n_mock.id(10),
/n/n/n/n/n/n/n/navatarUrl:/n_mock.image.avatar(index/n+/n6),
/n/n/n/n/n/n/n/nname:/n_mock.fullName(index/n+/n6),
/n/n/n/n/n/n},
/n/n/n/n/n/ncreatedAt:/n_mock.time(3),
/n/n/n/n/n/nmessage:
/n/n/n/n/n/n/n/n'Etiamrhoncus.Nullamvelsem.Pellentesqueliberotortor,tinciduntet,tincidunteget,sempernec,quam.Sedlectus.',
/n/n/n/n},
/n/n],
}));

exportconst_userCards/n=/n[...Array(21)].map((_,/nindex)/n=>/n({
/n/nid:/n_mock.id(index),
/n/nrole:/n_mock.role(index),
/n/nname:/n_mock.fullName(index),
/n/ncoverUrl:/n_mock.image.cover(index),
/n/navatarUrl:/n_mock.image.avatar(index),
/n/ntotalFollowers:/n_mock.number.nativeL(index),
/n/ntotalPosts:/n_mock.number.nativeL(index/n+/n2),
/n/ntotalFollowing:/n_mock.number.nativeL(index/n+/n1),
}));

exportconst_userPayment/n=/n[...Array(3)].map((_,/nindex)/n=>/n({
/n/nid:/n_mock.id(index),
/n/ncardNumber:/n['************1234',/n'************5678',/n'************7878'][index],
/n/ncardType:/n['mastercard',/n'visa',/n'visa'][index],
/n/nprimary:/nindex/n===/n1,
}));

exportconst_userAddressBook/n=/n[...Array(4)].map((_,/nindex)/n=>/n({
/n/nid:/n_mock.id(index),
/n/nprimary:/nindex/n===/n0,
/n/nname:/n_mock.fullName(index),
/n/nphoneNumber:/n_mock.phoneNumber(index),
/n/nfullAddress:/n_mock.fullAddress(index),
/n/naddressType:/n(index/n===/n0/n&&/n'Home')/n||/n'Office',
}));

exportconst_userInvoices/n=/n[...Array(10)].map((_,/nindex)/n=>/n({
/n/nid:/n_mock.id(index),
/n/ninvoiceNumber:/n`INV-199${index}`,
/n/ncreatedAt:/n_mock.time(index),
/n/nprice:/n_mock.number.price(index),
}));

exportconst_userPlans/n=/n[
/n/n{
/n/n/n/nsubscription:/n'basic',
/n/n/n/nprice:/n0,
/n/n/n/nprimary:/nfalse,
/n/n},
/n/n{
/n/n/n/nsubscription:/n'starter',
/n/n/n/nprice:/n4.99,
/n/n/n/nprimary:/ntrue,
/n/n},
/n/n{
/n/n/n/nsubscription:/n'premium',
/n/n/n/nprice:/n9.99,
/n/n/n/nprimary:/nfalse,
/n/n},
];

exportconst_userList/n=/n[...Array(20)].map((_,/nindex)/n=>/n({
/n/nid:/n_mock.id(index),
/n/nzipCode:/n'85807',
/n/nstate:/n'Virginia',
/n/ncity:/n'RanchoCordova',
/n/nrole:/n_mock.role(index),
/n/nemail:/n_mock.email(index),
/n/naddress:/n'908JackLocks',
/n/nname:/n_mock.fullName(index),
/n/nisVerified:/n_mock.boolean(index),
/n/ncompany:/n_mock.companyName(index),
/n/ncountry:/ncountries[index/n+/n1].label,
/n/navatarUrl:/n_mock.image.avatar(index),
/n/nphoneNumber:/n_mock.phoneNumber(index),
/n/nstatus:
/n/n/n/n(index/n%/n2/n&&/n'pending')/n||/n(index/n%/n3/n&&/n'banned')/n||/n(index/n%/n4/n&&/n'rejected')/n||/n'active',
}));
