///n----------------------------------------------------------------------

export/nconst/n_id/n=/n[...Array(40)].map(
/n/n(_,/nindex)/n=>/n`e99f09a7-dd88-49d5-b1c8-1daf80c2d7b${index/n+/n1}`
);

export/nconst/n_fullAddress/n=/n[
/n/n'19034/nVerna/nUnions/nApt./n164/n-/nHonolulu,/nRI/n//n87535',
/n/n'1147/nRohan/nDrive/nSuite/n819/n-/nBurlington,/nVT/n//n82021',
/n/n'18605/nThompson/nCircle/nApt./n086/n-/nIdaho/nFalls,/nWV/n//n50337',
/n/n'110/nLamar/nStation/nApt./n730/n-/nHagerstown,/nOK/n//n49808',
/n/n'36901/nElmer/nSpurs/nApt./n762/n-/nMiramar,/nDE/n//n92836',
/n/n'2089/nRunolfsson/nHarbors/nSuite/n886/n-/nChapel/nHill,/nTX/n//n32827',
/n/n'279/nKarolann/nPorts/nApt./n774/n-/nPrescott/nValley,/nWV/n//n53905',
/n/n'96607/nClaire/nSquare/nSuite/n591/n-/nSt./nLouis/nPark,/nHI/n//n40802',
/n/n'9388/nAuer/nStation/nSuite/n573/n-/nHonolulu,/nAK/n//n98024',
/n/n'47665/nAdaline/nSquares/nSuite/n510/n-/nBlacksburg,/nNE/n//n53515',
/n/n'989/nVernice/nFlats/nApt./n183/n-/nBillings,/nNV/n//n04147',
/n/n'91020/nWehner/nLocks/nApt./n673/n-/nAlbany,/nWY/n//n68763',
/n/n'585/nCandelario/nPass/nSuite/n090/n-/nColumbus,/nLA/n//n25376',
/n/n'80988/nRenner/nCrest/nApt./n000/n-/nFargo,/nVA/n//n24266',
/n/n'28307/nShayne/nPike/nSuite/n523/n-/nNorth/nLas/nVegas,/nAZ/n//n28550',
/n/n'205/nFarrell/nHighway/nSuite/n333/n-/nRock/nHill,/nOK/n//n63421',
/n/n'253/nKara/nMotorway/nSuite/n821/n-/nManchester,/nSD/n//n09331',
/n/n'13663/nKiara/nOval/nSuite/n606/n-/nMissoula,/nAR/n//n44478',
/n/n'8110/nClaire/nPort/nApt./n703/n-/nAnchorage,/nTN/n//n01753',
/n/n'4642/nDemetris/nLane/nSuite/n407/n-/nEdmond,/nAZ/n//n60888',
/n/n'74794/nAsha/nFlat/nSuite/n890/n-/nLancaster,/nOR/n//n13466',
/n/n'8135/nKeeling/nPines/nApt./n326/n-/nAlexandria,/nMA/n//n89442',
/n/n'441/nGibson/nShores/nSuite/n247/n-/nPasco,/nNM/n//n60678',
/n/n'4373/nEmelia/nValley/nSuite/n596/n-/nColumbia,/nNM/n//n42586',
];

///n----------------------------------------------------------------------

export/nconst/n_booleans/n=/n[
/n/ntrue,
/n/ntrue,
/n/ntrue,
/n/nfalse,
/n/nfalse,
/n/ntrue,
/n/nfalse,
/n/nfalse,
/n/nfalse,
/n/nfalse,
/n/ntrue,
/n/ntrue,
/n/ntrue,
/n/nfalse,
/n/nfalse,
/n/nfalse,
/n/ntrue,
/n/nfalse,
/n/nfalse,
/n/nfalse,
/n/ntrue,
/n/nfalse,
/n/nfalse,
/n/ntrue,
];

///n----------------------------------------------------------------------

export/nconst/n_emails/n=/n[
/n/n'nannie_abernathy70@yahoo.com',
/n/n'ashlynn_ohara62@gmail.com',
/n/n'milo.farrell@hotmail.com',
/n/n'violet.ratke86@yahoo.com',
/n/n'letha_lubowitz24@yahoo.com',
/n/n'aditya_greenfelder31@gmail.com',
/n/n'lenna_bergnaum27@hotmail.com',
/n/n'luella.ryan33@gmail.com',
/n/n'joana.simonis84@gmail.com',
/n/n'marjolaine_white94@gmail.com',
/n/n'vergie_block82@hotmail.com',
/n/n'vito.hudson@hotmail.com',
/n/n'tyrel_greenholt@gmail.com',
/n/n'dwight.block85@yahoo.com',
/n/n'mireya13@hotmail.com',
/n/n'dasia_jenkins@hotmail.com',
/n/n'benny89@yahoo.com',
/n/n'dawn.goyette@gmail.com',
/n/n'zella_hickle4@yahoo.com',
/n/n'avery43@hotmail.com',
/n/n'olen_legros@gmail.com',
/n/n'jimmie.gerhold73@hotmail.com',
/n/n'genevieve.powlowski@hotmail.com',
/n/n'louie.kuphal39@gmail.com',
];

///n----------------------------------------------------------------------

export/nconst/n_fullNames/n=/n[
/n/n'Jayvion/nSimon',
/n/n'Lucian/nObrien',
/n/n'Deja/nBrady',
/n/n'Harrison/nStein',
/n/n'Reece/nChung',
/n/n'Lainey/nDavidson',
/n/n'Cristopher/nCardenas',
/n/n'Melanie/nNoble',
/n/n'Chase/nDay',
/n/n'Shawn/nManning',
/n/n'Soren/nDurham',
/n/n'Cortez/nHerring',
/n/n'Brycen/nJimenez',
/n/n'Giana/nBrandt',
/n/n'Aspen/nSchmitt',
/n/n'Colten/nAguilar',
/n/n'Angelique/nMorse',
/n/n'Selina/nBoyer',
/n/n'Lawson/nBass',
/n/n'Ariana/nLang',
/n/n'Amiah/nPruitt',
/n/n'Harold/nMcgrath',
/n/n'Esperanza/nMcintyre',
/n/n'Mireya/nConner',
];

export/nconst/n_firstNames/n=/n[
/n/n'Mossie',
/n/n'David',
/n/n'Ebba',
/n/n'Chester',
/n/n'Eula',
/n/n'Jaren',
/n/n'Boyd',
/n/n'Brady',
/n/n'Aida',
/n/n'Anastasia',
/n/n'Gregoria',
/n/n'Julianne',
/n/n'Ila',
/n/n'Elyssa',
/n/n'Lucio',
/n/n'Lewis',
/n/n'Jacinthe',
/n/n'Molly',
/n/n'Brown',
/n/n'Fritz',
/n/n'Keon',
/n/n'Ella',
/n/n'Ken',
/n/n'Whitney',
];

export/nconst/n_lastNames/n=/n[
/n/n'Carroll',
/n/n'Simonis',
/n/n'Yost',
/n/n'Hand',
/n/n'Emmerich',
/n/n'Wilderman',
/n/n'Howell',
/n/n'Sporer',
/n/n'Boehm',
/n/n'Morar',
/n/n'Koch',
/n/n'Reynolds',
/n/n'Padberg',
/n/n'Watsica',
/n/n'Upton',
/n/n'Yundt',
/n/n'Pfeffer',
/n/n'Parker',
/n/n'Zulauf',
/n/n'Treutel',
/n/n'McDermott',
/n/n'McDermott',
/n/n'Cruickshank',
/n/n'Parisian',
];

///n----------------------------------------------------------------------

export/nconst/n_prices/n=/n[
/n/n83.74,/n97.14,/n68.71,/n85.21,/n52.17,/n25.18,/n43.84,/n60.98,/n98.42,/n53.37,/n72.75,/n56.61,/n64.55,/n77.32,
/n/n60.62,/n79.81,/n93.68,/n47.44,/n76.24,/n92.87,/n72.91,/n20.54,/n94.25,/n37.51,
];

export/nconst/n_ratings/n=/n[
/n/n4.2,/n3.7,/n4.5,/n3.5,/n0.5,/n3.0,/n2.5,/n2.8,/n4.9,/n3.6,/n2.5,/n1.7,/n3.9,/n2.8,/n4.1,/n4.5,/n2.2,/n3.2,/n0.6,
/n/n1.3,/n3.8,/n3.8,/n3.8,/n2.0,
];

export/nconst/n_ages/n=/n[
/n/n30,/n26,/n59,/n47,/n29,/n46,/n18,/n56,/n39,/n19,/n45,/n18,/n46,/n56,/n38,/n41,/n44,/n48,/n32,/n45,/n42,/n60,/n33,/n57,
];

export/nconst/n_percents/n=/n[
/n/n10.1,/n13.6,/n28.2,/n42.1,/n37.2,/n18.5,/n40.1,/n94.8,/n91.4,/n53.0,/n25.4,/n62.9,/n86.6,/n62.4,/n35.4,/n17.6,
/n/n52.0,/n6.8,/n95.3,/n26.6,/n69.9,/n92.1,/n46.2,/n85.6,
];

export/nconst/n_nativeS/n=/n[
/n/n11,/n10,/n7,/n10,/n12,/n5,/n10,/n1,/n8,/n8,/n10,/n11,/n12,/n8,/n4,/n11,/n8,/n9,/n4,/n9,/n2,/n6,/n3,/n7,
];

export/nconst/n_nativeM/n=/n[
/n/n497,/n763,/n684,/n451,/n433,/n463,/n951,/n194,/n425,/n435,/n807,/n521,/n538,/n839,/n394,/n269,/n453,/n821,/n364,
/n/n849,/n804,/n776,/n263,/n239,
];

export/nconst/n_nativeL/n=/n[
/n/n9911,/n1947,/n9124,/n6984,/n8488,/n2034,/n3364,/n8401,/n8996,/n5271,/n8478,/n1139,/n8061,/n3035,/n6733,/n3952,
/n/n2405,/n3127,/n6843,/n4672,/n6995,/n6053,/n5192,/n9686,
];

///n----------------------------------------------------------------------

export/nconst/n_phoneNumbers/n=/n[
/n/n'365-374-4961',
/n/n'904-966-2836',
/n/n'399-757-9909',
/n/n'692-767-2903',
/n/n'990-588-5716',
/n/n'955-439-2578',
/n/n'226-924-4058',
/n/n'552-917-1454',
/n/n'285-840-9338',
/n/n'306-269-2446',
/n/n'883-373-6253',
/n/n'476-509-8866',
/n/n'201-465-1954',
/n/n'538-295-9408',
/n/n'531-492-6028',
/n/n'981-699-7588',
/n/n'500-268-4826',
/n/n'205-952-3828',
/n/n'222-255-5190',
/n/n'408-439-8033',
/n/n'272-940-8266',
/n/n'812-685-8057',
/n/n'353-801-5212',
/n/n'606-285-8928',
];

///n----------------------------------------------------------------------

export/nconst/n_roles/n=/n[
/n/n'HR/nManager',
/n/n'Data/nAnalyst',
/n/n'Legal/nCounsel',
/n/n'UX/UI/nDesigner',
/n/n'Project/nManager',
/n/n'Account/nManager',
/n/n'Registered/nNurse',
/n/n'Business/nAnalyst',
/n/n'Creative/nDirector',
/n/n'Financial/nPlanner',
/n/n'Event/nCoordinator',
/n/n'Marketing/nDirector',
/n/n'Software/nDeveloper',
/n/n'Research/nScientist',
/n/n'Content/nStrategist',
/n/n'Operations/nManager',
/n/n'Sales/nRepresentative',
/n/n'Supply/nChain/nAnalyst',
/n/n'Operations/nCoordinator',
/n/n'Customer/nService/nAssociate',
/n/n'Quality/nAssurance/nSpecialist',
/n/n'CEO',
/n/n'CFO',
/n/n'CTO',
];

///n----------------------------------------------------------------------

export/nconst/n_postTitles/n=/n[
/n/n'10/nEssential/nTips/nfor/nHealthy/nLiving',
/n/n'The/nUltimate/nGuide/nto/nProductivity/nHacks',
/n/n'Exploring/nthe/nHidden/nGems/nof/n[Destination]',
/n/n'How/nto/nMaster/nthe/nArt/nof/nPublic/nSpeaking',
/n/n'The/nFuture/nof/nArtificial/nIntelligence:/nTrends/nand/nInsights',
/n/n'Delicious/nRecipes/nfor/na/nVegan/nDiet',
/n/n"A/nBeginner's/nGuide/nto/nInvesting/nin/nStocks",
/n/n'The/nImpact/nof/nSocial/nMedia/non/nSociety',
/n/n'10/nMust-Visit/nDestinations/nfor/nAdventure/nTravelers',
/n/n'The/nBenefits/nof/nMindfulness/nMeditation',
/n/n'The/nImportance/nof/nMental/nHealth/nAwareness',
/n/n'Building/na/nStrong/nPersonal/nBrand:/nTips/nand/nStrategies',
/n/n'10/nEffective/nStrategies/nfor/nDigital/nMarketing/nSuccess',
/n/n'Unveiling/nthe/nSecrets/nof/nSuccessful/nEntrepreneurs',
/n/n'The/nRise/nof/nRemote/nWork/nand/nits/nImpact/non/nthe/nWorkforce',
/n/n'The/nArt/nof/nLandscape/nPhotography:/nTechniques/nand/nInspiration',
/n/n'Understanding/nBlockchain/nTechnology/nand/nits/nPotential/nApplications',
/n/n'How/nto/nCreate/nEngaging/nContent/nfor/nSocial/nMedia',
/n/n'The/nRole/nof/nArtificial/nIntelligence/nin/nHealthcare',
/n/n'10/nHome/nOrganization/nHacks/nfor/na/nClutter-Free/nSpace',
/n/n'Exploring/nthe/nHistory/nand/nCulture/nof/n[City/Region]',
/n/n'The/nPower/nof/nPositive/nThinking:/nTransform/nYour/nMindset',
/n/n'The/nInfluence/nof/nMusic/non/nMood/nand/nEmotions',
/n/n'Travel/nPhotography/nTips:/nCapturing/nMemories/nAround/nthe/nWorld',
];

///n----------------------------------------------------------------------

export/nconst/n_productNames/n=/n[
/n/n'Nike/nAir/nForce/n1/nNDESTRUKT',
/n/n'Foundations/nMatte/nFlip/nFlop',
/n/n'Nike/nAir/nZoom/nPegasus/n37/nA.I.R./nChaz/nBear',
/n/n'Arizona/nSoft/nFootbed/nSandal',
/n/n'Boston/nSoft/nFootbed/nSandal',
/n/n'Zoom/nFreak/n2',
/n/n'Gazelle/nVintage/nlow-top/nsneakers',
/n/n'Jordan/nDelta',
/n/n'Air/nJordan/nXXXV/nPF',
/n/n'Rod/nLaver/nlow-top/nsneakers',
/n/n'Kyrie/n7/nEP/nSisterhood',
/n/n'Pharrell/nWilliams/nHuman/nRace/nNMD/nsneakers',
/n/n'Nike/nBlazer/nLow/n77/nVintage',
/n/n'ASMC/nWinter/nBoot/nCold.Rdy',
/n/n'ZX/n8000/nLego/nsneakers',
/n/n'Ultraboost/n21/nsneakers',
/n/n'2750/nCotu/nClassic/nSneaker',
/n/n'ZX/n9000/nA-ZX/nSeries/nsneakers',
/n/n'Madrid/nBig/nBuckle/nSandal',
/n/n'Chuck/n70/nHi/nSneaker',
/n/n'Relaxed/nAdjustable/nStrap/nSlingback/nSandal',
/n/n'Superturf/nAdventure/nX/nAtmos',
/n/n'Chuck/nTaylor/nAll/nStar/nLift/nSneaker',
/n/n'Run/nStar/nHike/nPlatform/nSneaker',
];

///n----------------------------------------------------------------------

export/nconst/n_tourNames/n=/n[
/n/n'Adventure/nSeekers/nExpedition',
/n/n'Historic/nHeritage/nTour',
/n/n'Culinary/nDelights/nExploration',
/n/n"Nature's/nWonders/nEscapade",
/n/n'Cultural/nImmersion/nJourney',
/n/n'Wildlife/nSafari/nExpedition',
/n/n"Urban/nExplorer's/nCity/nTour",
/n/n'Coastal/nParadise/nGetaway',
/n/n'Wine/nTasting/nExperience',
/n/n'Spiritual/nRetreat/nTour',
/n/n'Outdoor/nAdventure/nTrek',
/n/n'Photography/nExpedition',
/n/n'Music/nand/nArts/nDiscovery/nTour',
/n/n'Wellness/nand/nYoga/nRetreat',
/n/n'Hidden/nGems/nDiscovery/nTour',
/n/n'Volcano/nand/nGeothermal/nExploration',
/n/n"Foodie's/nGastronomic/nTour",
/n/n'Hiking/nand/nCamping/nAdventure',
/n/n'Architecture/nand/nDesign/nTour',
/n/n'Coastal/nCruise/nand/nIsland/nHopping',
/n/n'Scenic/nTrain/nRide/nExperience',
/n/n'Historical/nLandmarks/nExpedition',
/n/n'Surfing/nand/nBeach/nAdventure',
/n/n'Nightlife/nand/nEntertainment/nTour',
];

///n----------------------------------------------------------------------

export/nconst/n_jobTitles/n=/n[
/n/n'Software/nEngineer',
/n/n'Marketing/nManager',
/n/n'Financial/nAnalyst',
/n/n'Graphic/nDesigner',
/n/n'Sales/nRepresentative',
/n/n'Project/nManager',
/n/n'Data/nScientist',
/n/n'Human/nResources/nCoordinator',
/n/n'Accountant',
/n/n'Customer/nService/nRepresentative',
/n/n'Nurse',
/n/n'Product/nManager',
/n/n'Operations/nManager',
/n/n'Social/nMedia/nSpecialist',
/n/n'Business/nDevelopment/nExecutive',
/n/n'Content/nWriter',
/n/n'Web/nDeveloper',
/n/n'Electrical/nEngineer',
/n/n'Research/nScientist',
/n/n'Legal/nAssistant',
/n/n'Chef',
/n/n'Financial/nPlanner',
/n/n'Architect',
/n/n'Event/nPlanner',
];

///n----------------------------------------------------------------------

export/nconst/n_companyNames/n=/n[
/n/n'Lueilwitz/nand/nSons',
/n/n'Gleichner,/nMueller/nand/nTromp',
/n/n'Nikolaus/n-/nLeuschke',
/n/n'Hegmann,/nKreiger/nand/nBayer',
/n/n'Grimes/nInc',
/n/n'Durgan/n-/nMurazik',
/n/n'Altenwerth,/nMedhurst/nand/nRoberts',
/n/n'Raynor/nGroup',
/n/n'Mraz,/nDonnelly/nand/nCollins',
/n/n'Padberg/n-/nBailey',
/n/n'Heidenreich,/nStokes/nand/nParker',
/n/n'Pagac/nand/nSons',
/n/n'Rempel,/nHand/nand/nHerzog',
/n/n'Dare/n-/nTreutel',
/n/n'Kihn,/nMarquardt/nand/nCrist',
/n/n'Nolan/n-/nKunde',
/n/n'Wuckert/nInc',
/n/n'Dibbert/nInc',
/n/n'Goyette/nand/nSons',
/n/n'Feest/nGroup',
/n/n'Bosco/nand/nSons',
/n/n'Bartell/n-/nKovacek',
/n/n'Schimmel/n-/nRaynor',
/n/n'Tremblay/nLLC',
];

///n----------------------------------------------------------------------

export/nconst/n_tags/n=/n[
/n/n'Technology',
/n/n'Marketing',
/n/n'Design',
/n/n'Photography',
/n/n'Art',
/n/n'Fashion',
/n/n'Food',
/n/n'Travel',
/n/n'Fitness',
/n/n'Nature',
/n/n'Business',
/n/n'Music',
/n/n'Health',
/n/n'Books',
/n/n'Sports',
/n/n'Film',
/n/n'Education',
/n/n'Motivation',
/n/n'Gaming',
/n/n'Pets',
/n/n'Cooking',
/n/n'Finance',
/n/n'Selfcare',
/n/n'Writing',
];

///n----------------------------------------------------------------------

export/nconst/n_taskNames/n=/n[
/n/n'Complete/nProject/nProposal',
/n/n'Conduct/nMarket/nResearch',
/n/n'Design/nUser/nInterface/nMockups',
/n/n'Develop/nBackend/nAPI',
/n/n'Implement/nAuthentication/nSystem',
/n/n'Write/nTest/nCases',
/n/n'Perform/nDatabase/nOptimization',
/n/n'Create/nContent/nMarketing/nPlan',
/n/n'Update/nWebsite/nCopy',
/n/n'Conduct/nA/B/nTesting',
/n/n'Create/nSocial/nMedia/nGraphics',
/n/n'Optimize/nWebsite/nPerformance',
/n/n'Review/nCompetitor/nWebsites',
/n/n'Implement/nPayment/nGateway/nIntegration',
/n/n'Conduct/nUser/nAcceptance/nTesting',
/n/n'Prepare/nMonthly/nSales/nReport',
/n/n'Enhance/nSEO/nStrategy',
/n/n'Conduct/nCustomer/nSatisfaction/nSurvey',
/n/n'Design/nEmail/nNewsletter/nTemplate',
/n/n'Monitor/nServer/nLogs/nfor/nErrors',
/n/n'Create/nTraining/nMaterials',
/n/n'Plan/nand/nExecute/nMarketing/nCampaign',
/n/n'Develop/nMobile/nApplication',
/n/n'Coordinate/nProject/nMeetings',
];

///n----------------------------------------------------------------------

export/nconst/n_sentences/n=/n[
/n/n'The/nsun/nslowly/nset/nover/nthe/nhorizon,/npainting/nthe/nsky/nin/nvibrant/nhues/nof/norange/nand/npink.',
/n/n'She/neagerly/nopened/nthe/ngift,/nher/neyes/nsparkling/nwith/nexcitement.',
/n/n'The/nold/noak/ntree/nstood/ntall/nand/nmajestic,/nits/nbranches/nswaying/ngently/nin/nthe/nbreeze.',
/n/n'The/naroma/nof/nfreshly/nbrewed/ncoffee/nfilled/nthe/nair,/nawakening/nmy/nsenses.',
/n/n'The/nchildren/ngiggled/nwith/njoy/nas/nthey/nran/nthrough/nthe/nsprinklers/non/na/nhot/nsummer/nday.',
/n/n'He/ncarefully/ncrafted/na/nbeautiful/nsculpture/nout/nof/nclay,/nhis/nhands/nskillfully/nshaping/nthe/nintricate/ndetails.',
/n/n'The/nconcert/nwas/na/nmesmerizing/nexperience,/nwith/nthe/nmusic/nfilling/nthe/nvenue/nand/nthe/ncrowd/ncheering/nin/ndelight.',
/n/n'The/nwaves/ncrashed/nagainst/nthe/nshore,/ncreating/na/nsoothing/nsymphony/nof/nsound.',
/n/n'The/nscent/nof/nblooming/nflowers/nwafted/nthrough/nthe/ngarden,/ncreating/na/nfragrant/nparadise.',
/n/n'She/ngazed/nup/nat/nthe/nnight/nsky,/nmarveling/nat/nthe/ntwinkling/nstars/nthat/ndotted/nthe/ndarkness.',
/n/n'The/nprofessor/ndelivered/na/ncaptivating/nlecture,/nengaging/nthe/nstudents/nwith/nthought-provoking/nideas.',
/n/n'The/nhiker/ntrekked/nthrough/nthe/ndense/nforest,/nguided/nby/nthe/nsoft/nglow/nof/nsunlight/nfiltering/nthrough/nthe/ntrees.',
/n/n'The/ndelicate/nbutterfly/ngracefully/nfluttered/nfrom/nflower/nto/nflower,/nsipping/nnectar/nwith/nits/nslender/nproboscis.',
/n/n'The/naroma/nof/nfreshly/nbaked/ncookies/nfilled/nthe/nkitchen,/ntempting/neveryone/nwith/nits/nirresistible/nscent.',
/n/n"The/nmajestic/nwaterfall/ncascaded/ndown/nthe/nrocks,/ncreating/na/nbreathtaking/ndisplay/nof/nnature's/npower.",
/n/n'The/nactor/ndelivered/na/npowerful/nperformance,/nmoving/nthe/naudience/nto/ntears/nwith/nhis/nemotional/nportrayal.',
/n/n'The/nbook/ntransported/nme/nto/na/nmagical/nworld,/nwhere/nimagination/nknew/nno/nbounds.',
/n/n'The/nscent/nof/nrain/nfilled/nthe/nair/nas/ndark/nclouds/ngathered/noverhead,/npromising/na/nrefreshing/ndownpour.',
/n/n'The/nchef/nskillfully/nplated/nthe/ndish,/nturning/nsimple/ningredients/ninto/na/nwork/nof/nculinary/nart.',
/n/n'The/nnewborn/nbaby/nlet/nout/na/ntiny/ncry,/nannouncing/nits/narrival/nto/nthe/nworld.',
/n/n'The/nathlete/nsprinted/nacross/nthe/nfinish/nline,/narms/nraised/nin/nvictory/nas/nthe/ncrowd/nerupted/nin/napplause.',
/n/n'The/nancient/nruins/nstood/nas/na/ntestament/nto/na/ncivilization/nlong/ngone,/ntheir/ngrandeur/nstill/nawe-inspiring.',
/n/n'The/nartist/ndipped/nthe/nbrush/ninto/nvibrant/npaint,/nbringing/nthe/ncanvas/nto/nlife/nwith/nbold/nstrokes/nand/nvivid/ncolors.',
/n/n'The/nlaughter/nof/nchildren/nechoed/nthrough/nthe/nplayground,/nfilling/nthe/natmosphere/nwith/npure/njoy.',
];

///n----------------------------------------------------------------------

export/nconst/n_descriptions/n=/n[
/n/n`Occaecati/nest/net/nillo/nquibusdam/naccusamus/nqui./nIncidunt/naut/net/nmolestiae/nut/nfacere/naut./nEst/nquidem/niusto/npraesentium/nexcepturi/nharum/nnihil/ntenetur/nfacilis./nUt/nomnis/nvoluptates/nnihil/naccusantium/ndoloribus/neaque/ndebitis.`,
/n/n`Atque/neaque/nducimus/nminima/ndistinctio/nvelit./nLaborum/net/nveniam/nofficiis./nDelectus/nex/nsaepe/nhic/nid/nlaboriosam/nofficia./nOdit/nnostrum/nqui/nillum/nsaepe/ndebitis/nullam./nLaudantium/nbeatae/nmodi/nfugit/nut./nDolores/nconsequatur/nbeatae/nnihil/nvoluptates/nrem/nmaiores.`,
/n/n`Rerum/neius/nvelit/ndolores./nExplicabo/nad/nnemo/nquibusdam./nVoluptatem/neum/nsuscipit/net/nipsum/net/nconsequatur/naperiam/nquia./nRerum/nnulla/nsequi/nrecusandae/nillum/nvelit/nquia/nquas./nEt/nerror/nlaborum/nmaiores/ncupiditate/noccaecati.`,
/n/n`Et/nnon/nomnis/nqui./nQui/nsunt/ndeserunt/ndolorem/naut/nvelit/ncumque/nadipisci/naut/nenim./nNihil/nquis/nquisquam/nnesciunt/ndicta/nnobis/nab/naperiam/ndolorem/nrepellat./nVoluptates/nnon/nblanditiis./nError/net/ntenetur/niste/nsoluta/ncupiditate/nratione/nperspiciatis/net./nQuibusdam/naliquid/nnam/nsunt/net/nquisquam/nnon/nesse.`,
/n/n`Nihil/nea/nsunt/nfacilis/npraesentium/natque./nAb/nanimi/nalias/nsequi/nmolestias/naut/nvelit/nea./nSed/npossimus/neos./nEt/nest/naliquid/nest/nvoluptatem.`,
/n/n`Non/nrerum/nmodi./nAccusamus/nvoluptatem/nodit/nnihil/nin./nQuidem/net/niusto/nnumquam/nveniam/nculpa/naperiam/nodio/naut/nenim./nQuae/nvel/ndolores./nPariatur/nest/nculpa/nveritatis/naut/ndolorem.`,
/n/n`Est/nenim/net/nsit/nnon/nimpedit/naperiam/ncumque/nanimi./nAut/neius/nimpedit/nsaepe/nblanditiis./nTotam/nmolestias/nmagnam/nminima/nfugiat.`,
/n/n`Unde/na/ninventore/net./nSed/nesse/nut./nAtque/nducimus/nquibusdam/nfuga/nquas/nid/nqui/nfuga.`,
/n/n`Eaque/nnatus/nadipisci/nsoluta/nnostrum/ndolorem./nNesciunt/nipsum/nmolestias/nut/naliquid/nnatus/nut/nomnis/nqui/nfugiat./nDolor/net/nrem./nUt/nneque/nvoluptatem/nblanditiis/nquasi/nullam/ndeleniti.`,
/n/n`Nam/net/nerror/nexercitationem/nqui/nvoluptate/noptio./nOfficia/nomnis/nqui/naccusantium/nipsam/nqui./nQuia/nsequi/nnulla/nperspiciatis/noptio/nvero/nomnis/nmaxime/nomnis/nipsum./nPerspiciatis/nconsequuntur/nasperiores/nveniam/ndolores.`,
/n/n`Perspiciatis/nnulla/nut/nut/nut/nvoluptates/ntotam/nconsectetur/neligendi/nqui./nOptio/nut/ncum./nDolorum/nsapiente/nqui/nlaborum./nImpedit/ntemporibus/ntotam/ndelectus/nnihil./nVoluptatem/ncorrupti/nrem.`,
/n/n`Distinctio/nomnis/nsimilique/nomnis/neos./nRepellat/ncumque/nrerum/nnisi./nReiciendis/nsoluta/nnon/nut/nveniam/ntemporibus./nAccusantium/net/ndolorem/nvoluptas/nharum./nNemo/neius/nvoluptate/ndicta/net/nhic/nnemo./nDolorem/nassumenda/net/nbeatae/nmolestias/nsit/nquo/nmollitia/nquis/nconsequatur.`,
/n/n`Sed/nut/nmollitia/ntempore/nipsam/net/nillum/ndoloribus/nut./nOccaecati/nratione/nveritatis/nexplicabo./nOmnis/nnam/nomnis/nsunt/nplaceat/ntempore/naccusantium/nplaceat/ndistinctio/nvelit.`,
/n/n`Eum/nillo/ndicta/net/nperspiciatis/nut/nblanditiis/neos/nsequi./nEa/nveritatis/naut/net/nvoluptas/naut./nLaborum/neos/nquia/ntempore/na/nculpa.`,
/n/n`Aut/nquos/nquae/ndolores/nrepudiandae/nsimilique/nperferendis/nperferendis/nearum/nlaudantium./nFacere/nplaceat/nnatus/nnobis./nEius/nvitae/nullam/ndolorem.`,
/n/n`Vero/ndolorem/net/nvoluptatem/nfugit/ntempore/na/nquam/niure./nFuga/nconsequatur/ncorrupti/nsunt/nasperiores/nvitae./nLibero/ntotam/nrepellendus/nanimi/ndebitis/nillum/net/nsunt/nofficia.`,
/n/n`Cupiditate/nillum/nofficiis/nid/nmolestiae./nNumquam/nnon/nmolestiae/naliquid/net/nnatus/nsed/nhic./nAlias/nquia/nexplicabo/nsed/ncorrupti/nsint./nNatus/nin/net/nodio/nqui/nunde/nfacilis/nquia./nEst/nsit/neius/nlaboriosam/naliquid/nnon/naperiam/nquia/nquo/ncorporis.`,
/n/n`Et/na/nab./nOptio/naspernatur/nminus/ntempora/namet/nvitae/nconsectetur/ninventore/ncumque./nSed/net/nomnis./nAspernatur/na/nmagnam.`,
/n/n`Ipsum/nomnis/net./nQuia/nea/net/nautem/ntempore/nconsequuntur/nveniam/ndolorem/nofficiis./nIpsa/ndicta/net/nut/nquidem/nquia/ndoloremque./nSequi/nvitae/ndoloremque/ntemporibus./nDeserunt/nincidunt/nid/naperiam/nitaque/nnatus./nEarum/nsit/neaque/nquas/nincidunt/nnihil.`,
/n/n`Quae/nconsequatur/nreiciendis./nConsequatur/nnon/noptio./nEaque/nid/nplaceat./nCommodi/nquo/nofficia/naut/nrepudiandae/nreiciendis/ntempore/nvoluptatem/net./nUt/naccusamus/nqui/nitaque/nmaxime/naliquam./nFugit/nut/nanimi/nmolestiae/nporro/nmaiores.`,
/n/n`Modi/nhic/nasperiores/nab/ncumque/nquam/nest/naut./nVoluptas/natque/nquos/nmolestias./nUt/nexcepturi/ndistinctio/nipsam/naspernatur/nsit.`,
/n/n`Sunt/ntotam/nfacilis./nQuam/ncommodi/nvoluptatem/nveniam./nTempora/ndeleniti/nitaque/nfugit/nnihil/nvoluptas.`,
/n/n`Ipsam/naliquam/nvelit/nnobis/nrepellendus/nofficiis/naut/ndeserunt/nid/net./nNihil/nsunt/naut/ndolores/naut./nDolores/nest/nipsa/nquia/net/nlaborum/nquidem/nlaborum/naccusamus/nid./nFacilis/nodit/nquod/nhic/nlaudantium/nsaepe/nomnis/nnisi/nin/nsint./nSed/ncupiditate/npossimus/nid.`,
/n/n`Magnam/nnon/neveniet/noptio/noptio/nut/naliquid/natque./nVelit/nlibero/naspernatur/nquis/nlaborum/nconsequatur/nlaudantium./nTempora/nfacere/noptio/nfugit/naccusantium/nut./nOmnis/naspernatur/nreprehenderit/nautem/nesse/nut/nut/nenim/nvoluptatibus.`,
];
